### ISSUE TITLE
How to create Gradient Vector Fields?

### ISSUE THREAD

**Issue by andylikh** [keijiro/VfxGraphTestbed#3]
First of all, I love all of your work. 

But the biggest question when looking at your work is how do you create these Gradient VF files that a lot of your particles seems to mesh around?

![image](https://user-images.githubusercontent.com/39035665/67428644-6eaabb00-f5d6-11e9-85c9-6e95dc1abe7d.png)

Much appreciated!

**Comment by keijiro** [comment]
I think you're referring to a wrong repository. If you're asking about [VectorFieldExamples](https://github.com/keijiro/VectorFieldExamples), please refer to this issue: https://github.com/keijiro/VectorFieldExamples/issues/1

**Comment by keijiro** [comment]
I'm closing this issue now as irrelevant to the repository contents. Please feel free to reopen for further questions.
